package vn.edu.huce.iic.bts_ops_platform.modules.core.cauhinh.exception;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import vn.edu.huce.iic.bts_ops_platform.common.dto.ExceptionCode;

@Getter
@RequiredArgsConstructor
public enum CauHinhErrorCode implements ExceptionCode {

    LOAI_HOP_DONG_NOT_FOUND(404, "LOAI_HOP_DONG_NOT_FOUND", HttpStatus.NOT_FOUND),
    LOAI_HOP_DONG_CODE_EXISTS(409, "LOAI_HOP_DONG_CODE_EXISTS", HttpStatus.CONFLICT),
    KIEU_HOP_DONG_NOT_FOUND(404, "KIEU_HOP_DONG_NOT_FOUND", HttpStatus.NOT_FOUND),
    KIEU_HOP_DONG_CODE_EXISTS(409, "KIEU_HOP_DONG_CODE_EXISTS", HttpStatus.CONFLICT),
    DOI_TUONG_QUAN_LY_NOT_FOUND(404, "DOI_TUONG_QUAN_LY_NOT_FOUND", HttpStatus.NOT_FOUND),
    DOI_TUONG_QUAN_LY_CODE_EXISTS(409, "DOI_TUONG_QUAN_LY_CODE_EXISTS", HttpStatus.CONFLICT),
    DOI_TUONG_HOP_DONG_LIEN_KET_NOT_FOUND(404, "DOI_TUONG_HOP_DONG_LIEN_KET_NOT_FOUND", HttpStatus.NOT_FOUND),
    DOI_TUONG_HOP_DONG_LIEN_KET_INVALID(400, "DOI_TUONG_HOP_DONG_LIEN_KET_INVALID", HttpStatus.BAD_REQUEST),
    LIEN_KET_HOP_DONG_NOT_FOUND(404, "LIEN_KET_HOP_DONG_NOT_FOUND", HttpStatus.NOT_FOUND),
    LIEN_KET_HOP_DONG_INVALID(400, "LIEN_KET_HOP_DONG_INVALID", HttpStatus.BAD_REQUEST),
    LIEN_KET_HOP_DONG_EXISTS(409, "LIEN_KET_HOP_DONG_EXISTS", HttpStatus.CONFLICT),
    TRANG_THAI_HOP_DONG_NOT_FOUND(404, "TRANG_THAI_HOP_DONG_NOT_FOUND", HttpStatus.NOT_FOUND),
    TRANG_THAI_HOP_DONG_CODE_EXISTS(409, "TRANG_THAI_HOP_DONG_CODE_EXISTS", HttpStatus.CONFLICT),
    KIEU_DU_LIEU_NOT_FOUND(404, "KIEU_DU_LIEU_NOT_FOUND", HttpStatus.NOT_FOUND),
    KIEU_DU_LIEU_CODE_EXISTS(409, "KIEU_DU_LIEU_CODE_EXISTS", HttpStatus.CONFLICT),
    THUOC_TINH_NOT_FOUND(404, "THUOC_TINH_NOT_FOUND", HttpStatus.NOT_FOUND),
    THUOC_TINH_TUY_CHON_REQUIRED(400, "THUOC_TINH_TUY_CHON_REQUIRED", HttpStatus.BAD_REQUEST),
    THUOC_TINH_CODE_EXISTS(409, "THUOC_TINH_CODE_EXISTS", HttpStatus.CONFLICT),
    THUOC_TINH_LOAI_HOP_DONG_NOT_FOUND(404, "THUOC_TINH_LOAI_HOP_DONG_NOT_FOUND", HttpStatus.NOT_FOUND),
    THUOC_TINH_HOP_DONG_NOT_FOUND(404, "THUOC_TINH_HOP_DONG_NOT_FOUND", HttpStatus.NOT_FOUND),
    THUOC_TINH_KIEU_HOP_DONG_NOT_FOUND(404, "THUOC_TINH_KIEU_HOP_DONG_NOT_FOUND", HttpStatus.NOT_FOUND),
    THUOC_TINH_KIEU_HOP_DONG_INVALID(400, "THUOC_TINH_KIEU_HOP_DONG_INVALID", HttpStatus.BAD_REQUEST),
    HOP_DONG_TRANG_THAI_NOT_FOUND(404, "HOP_DONG_TRANG_THAI_NOT_FOUND", HttpStatus.NOT_FOUND),
    HOP_DONG_TRANG_THAI_CODE_EXISTS(409, "HOP_DONG_TRANG_THAI_CODE_EXISTS", HttpStatus.CONFLICT),
    LUONG_TRANG_THAI_NOT_FOUND(404, "LUONG_TRANG_THAI_NOT_FOUND", HttpStatus.NOT_FOUND),
    KIEU_HOP_DONG_LUONG_TRANG_THAI_NOT_FOUND(404, "KIEU_HOP_DONG_LUONG_TRANG_THAI_NOT_FOUND", HttpStatus.NOT_FOUND),
    DANH_MUC_BIEN_BAN_NOT_FOUND(404, "DANH_MUC_BIEN_BAN_NOT_FOUND", HttpStatus.NOT_FOUND),
    DANH_MUC_BIEN_BAN_CODE_EXISTS(409, "DANH_MUC_BIEN_BAN_CODE_EXISTS", HttpStatus.CONFLICT),
    KIEU_HOP_DONG_DANH_MUC_BIEN_BAN_NOT_FOUND(404, "KIEU_HOP_DONG_DANH_MUC_BIEN_BAN_NOT_FOUND", HttpStatus.NOT_FOUND),
    ;

    private final int code;
    private final String type;
    private final HttpStatus httpStatus;

    @Override
    public Integer getCode() {
        return code;
    }

    @Override
    public String getType() {
        return type;
    }

    @Override
    public HttpStatus getHttpStatus() {
        return httpStatus;
    }
}
