package vn.edu.huce.iic.bts_ops_platform.modules.core.hopdong.base.exception;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import vn.edu.huce.iic.bts_ops_platform.common.dto.ExceptionCode;

@Getter
@RequiredArgsConstructor
public enum HopDongErrorCode implements ExceptionCode {

    HOP_DONG_NOT_FOUND(404, "HOP_DONG_NOT_FOUND", HttpStatus.NOT_FOUND),
    HOP_DONG_CODE_EXISTS(409, "HOP_DONG_CODE_EXISTS", HttpStatus.CONFLICT),
    HOP_DONG_THUOC_TINH_NOT_FOUND(404, "HOP_DONG_THUOC_TINH_NOT_FOUND", HttpStatus.NOT_FOUND),
    HOP_DONG_THUOC_TINH_CODE_EXISTS(409, "HOP_DONG_THUOC_TINH_CODE_EXISTS", HttpStatus.CONFLICT),
    HOP_DONG_THUOC_TINH_INVALID(400, "HOP_DONG_THUOC_TINH_INVALID", HttpStatus.BAD_REQUEST),
    HOP_DONG_TEP_DINH_KEM_NOT_FOUND(404, "HOP_DONG_TEP_DINH_KEM_NOT_FOUND", HttpStatus.NOT_FOUND),
    HOP_DONG_TEP_DINH_KEM_CODE_EXISTS(409, "HOP_DONG_TEP_DINH_KEM_CODE_EXISTS", HttpStatus.CONFLICT),
    HOP_DONG_NHOM_UU_TIEN_NOT_FOUND(404, "HOP_DONG_NHOM_UU_TIEN_NOT_FOUND", HttpStatus.NOT_FOUND),
    HOP_DONG_NHOM_UU_TIEN_CODE_EXISTS(409, "HOP_DONG_NHOM_UU_TIEN_CODE_EXISTS", HttpStatus.CONFLICT),
    HOP_DONG_DOI_TUONG_NOT_FOUND(404, "HOP_DONG_DOI_TUONG_NOT_FOUND", HttpStatus.NOT_FOUND),
    HOP_DONG_DOI_TUONG_CODE_EXISTS(409, "HOP_DONG_DOI_TUONG_CODE_EXISTS", HttpStatus.CONFLICT),
    HOP_DONG_DOI_TUONG_INVALID(400, "HOP_DONG_DOI_TUONG_INVALID", HttpStatus.BAD_REQUEST),
    HOP_DONG_DOI_TUONG_CAU_HINH_THIEU(400, "HOP_DONG_DOI_TUONG_CAU_HINH_THIEU", HttpStatus.BAD_REQUEST),
    HOP_DONG_DOI_TUONG_GIA_TRI_NOT_FOUND(404, "HOP_DONG_DOI_TUONG_GIA_TRI_NOT_FOUND", HttpStatus.NOT_FOUND),
    HOP_DONG_DOI_TUONG_GIA_TRI_CODE_EXISTS(409, "HOP_DONG_DOI_TUONG_GIA_TRI_CODE_EXISTS", HttpStatus.CONFLICT),
    HOP_DONG_DOI_TUONG_TRANG_THAI_NOT_FOUND(404, "HOP_DONG_DOI_TUONG_TRANG_THAI_NOT_FOUND", HttpStatus.NOT_FOUND),
    HOP_DONG_DOI_TUONG_TRANG_THAI_CODE_EXISTS(409, "HOP_DONG_DOI_TUONG_TRANG_THAI_CODE_EXISTS", HttpStatus.CONFLICT),
    HOP_DONG_CANCELLED(400, "HOP_DONG_CANCELLED", HttpStatus.BAD_REQUEST),
    BIEN_BAN_NOT_FOUND(404, "BIEN_BAN_NOT_FOUND", HttpStatus.NOT_FOUND),
    BIEN_BAN_INVALID(400, "BIEN_BAN_INVALID", HttpStatus.BAD_REQUEST),
    CHINH_SUA_THONG_SO_NOT_FOUND(404, "CHINH_SUA_THONG_SO_NOT_FOUND", HttpStatus.NOT_FOUND),
    CHINH_SUA_THONG_SO_INVALID(400, "CHINH_SUA_THONG_SO_INVALID", HttpStatus.BAD_REQUEST),
    CHINH_SUA_THONG_SO_CAN_PHE_DUYET(400, "CHINH_SUA_THONG_SO_CAN_PHE_DUYET", HttpStatus.BAD_REQUEST),
    CHINH_SUA_THONG_SO_CHO_DUYET(409, "CHINH_SUA_THONG_SO_CHO_DUYET", HttpStatus.CONFLICT),
    ;

    private final int code;
    private final String type;
    private final HttpStatus httpStatus;

    @Override
    public Integer getCode() {
        return code;
    }

    @Override
    public String getType() {
        return type;
    }

    @Override
    public HttpStatus getHttpStatus() {
        return httpStatus;
    }
}
